### Understand behavior of Batch Normalization of pytorch 1.8.2, below is the document from pytorch

https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html?highlight=batchnorm2d#torch.nn.BatchNorm2d

In [5]:
import torch
import torch.nn as nn
m = nn.BatchNorm2d(2, affine = False, momentum = 0.1, track_running_stats = True)
input1 = torch.tensor(
    [[[[1., 1.],
       [1., 1.]],
      [[1., 1.],
       [1., 1.]]], 
     [[[2., 2.], 
       [2., 2.]], 
      [[4., 4.], 
       [4., 3.]]]])
print(input1.shape)
for i in range(100):
    # print(m.running_mean, m.running_var, m.momentum)
    o = m(input1)
print("after many batches and before call eval(), running_mean and running_var :", m.running_mean, m.running_var, m.momentum)
m.eval()
print("after many batches and after call eval(),  running_mean and running_var :", m.running_mean, m.running_var, m.momentum)

# torch.Size([2, 2, 2, 2])
# after many batches and before call eval(), running_mean and running_var : tensor([1.5000, 2.3749]) tensor([0.2857, 2.2678]) 0.1
# after many batches and after call eval(), running_mean and running_var : tensor([1.5000, 2.3749]) tensor([0.2857, 2.2678]) 0.1
# (4 + 4 + 4 + 3 + 1 + 1 + 1 + 1) / 8 = 2.3749

input1 = torch.tensor(
    [[[[1., 1.],
       [1., 1.]],
      [[2., 2.],
       [2., 2.]]]])

torch.set_printoptions(precision=4, sci_mode=False)
print("BatchNorm2d eval input1: \n", m(input1))

# output, note: (1.0 - 1.5) / ((0.2857) ** 0.5) == -0.9353
#               (2.0 - 2.3749) /((2.2678) ** 0.5) == -0.249
# tensor([[[[-0.9353, -0.9353],
#           [-0.9353, -0.9353]],

#          [[-0.2490, -0.2490],
#           [-0.2490, -0.2490]]]])



torch.Size([2, 2, 2, 2])
after many batches and before call eval(), running_mean and running_var : tensor([1.5000, 2.3749]) tensor([0.2857, 2.2678]) 0.1
after many batches and after call eval(),  running_mean and running_var : tensor([1.5000, 2.3749]) tensor([0.2857, 2.2678]) 0.1
BatchNorm2d eval input1: 
 tensor([[[[-0.9353, -0.9353],
          [-0.9353, -0.9353]],

         [[-0.2490, -0.2490],
          [-0.2490, -0.2490]]]])


In [6]:
import torch
import torch.nn as nn
m = nn.BatchNorm2d(2, affine = False, momentum = 0.1, track_running_stats = True)
input1 = torch.tensor(
    [[[[1., 1., 1.]],
      [[2., 2., 2.]]], 
     [[[3., 3., 3.]], 
      [[4., 4., 4.]]]])
print(input1.shape)
for i in range(100):
    # print(m.running_mean, m.running_var, m.momentum)
    o = m(input1)
print("after many batches and before call eval(), running_mean and running_var :", m.running_mean, m.running_var, m.momentum)
m.eval()
print("after many batches and after call eval(),  running_mean and running_var :", m.running_mean, m.running_var, m.momentum)

# torch.Size([2, 2, 1, 3])
# after many batches and before call eval(), running_mean and running_var : tensor([1.9999, 2.9999]) tensor([1.2000, 1.2000]) 0.1
# after many batches and after call eval(),  running_mean and running_var : tensor([1.9999, 2.9999]) tensor([1.2000, 1.2000]) 0.1

# (4 + 4 + 4 + 2 + 2 + 2) / 6 = 2.9999

input1 = torch.tensor(
    [[[[1., 1.],
       [1., 1.]],
      [[2., 2.],
       [2., 2.]]]])

torch.set_printoptions(precision=4, sci_mode=False)
print("BatchNorm2d eval input1: \n", m(input1))

# output, note: (1.0 - 1.9999) / ((1.2) ** 0.5) == -0.9128
#               (2.0 - 2.9999) / ((1.2) ** 0.5) == -0.9128
# tensor([[[[-0.9128, -0.9128],
#           [-0.9128, -0.9128]],

#          [[-0.9128, -0.9128],
#           [-0.9128, -0.9128]]]])



torch.Size([2, 2, 1, 3])
after many batches and before call eval(), running_mean and running_var : tensor([1.9999, 2.9999]) tensor([1.2000, 1.2000]) 0.1
after many batches and after call eval(),  running_mean and running_var : tensor([1.9999, 2.9999]) tensor([1.2000, 1.2000]) 0.1
BatchNorm2d eval input1: 
 tensor([[[[-0.9128, -0.9128],
          [-0.9128, -0.9128]],

         [[-0.9128, -0.9128],
          [-0.9128, -0.9128]]]])
