In [11]:
import torch
t = torch.tensor([1, 2, 2, 3, 5])
mask = torch.tensor([True, True, False, False, True])
print(t)
print(t[mask])

print(t == 2)
print(sum(t == 2))

print(torch.where(t == 2))
print(torch.where(t == 5))
print(torch.where(t == 6))

tensor([1, 2, 2, 3, 5])
tensor([1, 2, 5])
tensor([False,  True,  True, False, False])
tensor(2)
(tensor([1, 2]),)
(tensor([4]),)
(tensor([], dtype=torch.int64),)
