In [9]:
# Module.to: This method modifies the module ***in-place****. We should change back after this call.
import torch
linear = torch.nn.Linear(5, 3, dtype=torch.float32)
for p in linear.parameters():
    print(p.dtype)

linear.to(torch.float16) # eq to linear.half()

for p in linear.parameters():
    print(p.dtype)

t = torch.tensor([2.1, 2.2], dtype=torch.float32)
print(t.half()) # return a new tensor without modifying t
print(t.to(dtype=torch.float16)) # return a new tensor without modifying t
print(t, t.dtype)

torch.float32
torch.float32
torch.float16
torch.float16
tensor([2.0996, 2.1992], dtype=torch.float16)
tensor([2.0996, 2.1992], dtype=torch.float16)
tensor([2.1000, 2.2000]) torch.float32
